ebook_metadata:
  title: བློ་གྲོས་མཐའ་ཡས་པའི་མཛོད།
  authors:
  - མཛད་པ་པོ། ཡོངས་འཛིན་རྣམ་རྒྱལ་གྲགས་པ།
  - མཛད་པ་པོ། ཤཱཀྱ་མཆོག་ལྡན་དྲི་མེད་ལེགས་པའི་བློ་གྲོས།
  sku: RDI-SS-12
  layers:
  - book_title
  - author
  - chapter_title
  - tsawa
  - quotation
  - sabche
web_metadata:
  title:
    en: “The Lapis Lazuli Stairway”:The Entry to the Ocean of Texts on Reasoning
    bo: རིགས་གཞུང་རྒྱ་མཚོའི་འཇུག་ངོགས་བཻཌཱུརྱའི་ཐེམ་སྐས།
  collection:
    en: RDI Study Series–  Book 12
    bo: ཐོས་བསམ་འཆད་ཉན་གྱི་རིམ་པ།–  དེབ། ༡༢
  author:
    en: 'Authors:'
    bo: ཡོངས་འཛིན་རྣམ་རྒྱལ་གྲགས་པ།,ཤཱཀྱ་མཆོག་ལྡན་དྲི་མེད་ལེགས་པའི་བློ་གྲོས།
  pusblisher:
    en: ''
    bo: རིག་པའི་རྡོ་རྗེ་གཙུག་ལག་སློབ་ཉེར་ཁང་།
  sku: RDI-SS-12
  category:
    en: Valid Cognition
    bo: ཚད་མ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: RDI-SS-12.epub
  description:
    en: ༄༅། །འདིར་བསམ་སྦྱོར་ཡང་དག་པའི་སྒོ་ནས་འབྲས་བུ་མཐར་ཐུག་པ་བླ་མེད་བྱང་ཆེན་ལ་བགྲོད་པའི་ལམ་མ་ནོར་བར་སྟོན་མཁན་ནི་སངས་རྒྱས་ཉག་གཅིག་ཡིན་ལ།
      ཐབས་ལ་མཁས་ཤིང་ཐུགས་རྗེ་ཆེ་བའི་སྟོན་པ་དེ་ཉིད་ཀྱིས་གདུལ་བྱའི་ཚོགས་རྣམས་ཐར་པའི་ལམ་ལ་བཀྲི་བའི་ཐབས་སུ་དྲང་ངེས་ཀྱི་ཚུལ་སྣ་ཚོགས་གསུངས་པས་དེ་དག་སྒྲ་ཇི་བཞིན་ཡིན་མིན་དང་།
      བརྗོད་བྱ་གནས་ལུགས་སྟོན་མིན་སོགས་ཀྱིས་གསུང་རབ་ནང་ཕན་ཚུན་སྒྲས་ཟིན་གྱི་བརྗོད་ཚུལ་ལ་འགལ་བ་ལྟར་སྣང་ཡང་དོན་ལ་དགོངས་པ་གཅིག་ཏུ་གནས་ཏེ།
      ཆུ་བོ་ཐམས་ཅད་རྒྱ་མཚོ་ལ་འབབ་པ་བཞིན་ཆོས་ཚུལ་མཐའ་དག་སྟོང་ཉིདལ་གཞོལ་ཞིང་འབབ་པའོ།
      །ཞེས་གསུངས་པ་བཞིན། ཆོས་ཚུལ་དེ་དག་སྟོང་ཉིད་རྟོགས་པའི་ཐབས་འབའ་ཞིག་ཡིན་ནོ། །དེ་ལྟར་བསྟན་པ་ཐམས་ཅད་འགལ་མེད་དུ་རྟོགས་ཤིང་།
      གསུང་རབ་ཐམས་ཅད་གདམས་ངག་ཏུ་འཆར་བའི་ཐབས་གཅིག་པུར་གྱུར་པ་ནི་རིགས་པའི་ལམ་ནས་གསུང་རབ་ཀྱི་དགོངས་པ་འཚོལ་བ་ཉིད་ཡིན་ནོ།
      །
    bo: ༄༅། །འདིར་བསམ་སྦྱོར་ཡང་དག་པའི་སྒོ་ནས་འབྲས་བུ་མཐར་ཐུག་པ་བླ་མེད་བྱང་ཆེན་ལ་བགྲོད་པའི་ལམ་མ་ནོར་བར་སྟོན་མཁན་ནི་སངས་རྒྱས་ཉག་གཅིག་ཡིན་ལ།
      ཐབས་ལ་མཁས་ཤིང་ཐུགས་རྗེ་ཆེ་བའི་སྟོན་པ་དེ་ཉིད་ཀྱིས་གདུལ་བྱའི་ཚོགས་རྣམས་ཐར་པའི་ལམ་ལ་བཀྲི་བའི་ཐབས་སུ་དྲང་ངེས་ཀྱི་ཚུལ་སྣ་ཚོགས་གསུངས་པས་དེ་དག་སྒྲ་ཇི་བཞིན་ཡིན་མིན་དང་།
      བརྗོད་བྱ་གནས་ལུགས་སྟོན་མིན་སོགས་ཀྱིས་གསུང་རབ་ནང་ཕན་ཚུན་སྒྲས་ཟིན་གྱི་བརྗོད་ཚུལ་ལ་འགལ་བ་ལྟར་སྣང་ཡང་དོན་ལ་དགོངས་པ་གཅིག་ཏུ་གནས་ཏེ།
      ཆུ་བོ་ཐམས་ཅད་རྒྱ་མཚོ་ལ་འབབ་པ་བཞིན་ཆོས་ཚུལ་མཐའ་དག་སྟོང་ཉིདལ་གཞོལ་ཞིང་འབབ་པའོ།
      །ཞེས་གསུངས་པ་བཞིན། ཆོས་ཚུལ་དེ་དག་སྟོང་ཉིད་རྟོགས་པའི་ཐབས་འབའ་ཞིག་ཡིན་ནོ། །དེ་ལྟར་བསྟན་པ་ཐམས་ཅད་འགལ་མེད་དུ་རྟོགས་ཤིང་།
      གསུང་རབ་ཐམས་ཅད་གདམས་ངག་ཏུ་འཆར་བའི་ཐབས་གཅིག་པུར་གྱུར་པ་ནི་རིགས་པའི་ལམ་ནས་གསུང་རབ་ཀྱི་དགོངས་པ་འཚོལ་བ་ཉིད་ཡིན་ནོ།
      །
